remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Young Security Inc
description: Over 20 years of experience providing exceptional cybersecurity services to organizations and individuals.
show_downloads: false # ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: # [Your Google Analytics tracking ID]
collections:
  authors:
    output: true
  members:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
